### ISSUE TITLE
need flag to process raw string with jq

### ISSUE THREAD

**Issue by alingse** [CyberAgent/hive-jq-udtf#3]
just like https://stedolan.github.io/jq/manual/ --raw-input/-R:

we want to process raw string use `contains`

the query like this.

```SQL
CREATE TEMPORARY FUNCTION jq AS 'jp.co.cyberagent.hive.udtf.jsonquery.v3.JsonQueryUDTF';
 
SELECT
  jq(
    '"helloworldis"',
    '["e", "o"] as $keys|range(0, $keys|length) as $index|[$keys[$index], contains($keys[$index])|tostring]',
    'array<string>'
  );
```

and the `'"helloworld"'` must be escape  with `"`, not `'helloworld'`

**Comment by eiiches** [comment]
Hi @alingse 

I think what you need here is a UDF to convert Hive types to JSON strings. After some googling I found this:

https://github.com/klout/brickhouse/blob/863a370820f64a7825c337f708116149978c097a/src/main/java/brickhouse/udf/json/ToJsonUDF.java

I've never used it before but you can probably use it like this:

```sql
SELECT jq(to_json('helloworldis'), ...)
```

**Comment by alingse** [comment]
yes, we use the `to_json` finally . 😄   thx a lot.
